repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        fail_fast: true
      - id: check-added-large-files
        fail_fast: true

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: venv/bin/python -m mypy
        language: script
        require_serial: true
        pass_filenames: false
        fail_fast: true

      - id: black
        name: black
        entry: venv/bin/python -m black --check
        language: script
        types: [python]
        fail_fast: true

      - id: isort
        name: isort
        entry: venv/bin/python -m isort --check
        language: script
        types: [python]
        fail_fast: true

      - id: flake8
        name: flake8
        entry: venv/bin/python -m flake8
        language: script
        types: [python]
        fail_fast: true

      - id: pytest_tox
        name: pytest_tox
        entry: venv/bin/python -m tox -p auto
        language: script
        require_serial: true
        pass_filenames: false