repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: venv/bin/python -m mypy
        language: script
        require_serial: true
        pass_filenames: false

      - id: black
        name: black
        entry: venv/bin/python -m black --check
        language: script
        types: [python]

      - id: isort
        name: isort
        entry: venv/bin/python -m isort --check
        language: script
        types: [python]

      - id: flake8
        name: flake8
        entry: venv/bin/python -m flake8
        language: script
        types: [python]

      - id: pytest_tox
        name: pytest_tox
        entry: venv/bin/python -m tox
        language: script
        require_serial: true
        pass_filenames: false