import pytest

from tests.mongo.shared_test_propagation import test_mandatory_propagation as test_mandatory_propagation
from tests.mongo.shared_test_propagation import test_nested_propagation as test_nested_propagation
from tests.mongo.shared_test_propagation import test_never_propagation as test_never_propagation
from tests.mongo.shared_test_propagation import test_not_supported_propagation as test_not_supported_propagation
from tests.mongo.shared_test_propagation import test_required_propagation as test_required_propagation
from tests.mongo.shared_test_propagation import test_requires_new_propagation as test_requires_new_propagation
from tests.mongo.shared_test_propagation import test_supports_propagation as test_supports_propagation

pytestmark = [pytest.mark.asyncio, pytest.mark.integration]
